language: cpp

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
